feat: add svelte support
antfu/unplugin-icons pull request #49
Opened 2021-09-13 11:33 UTC by userquin

This PR adds support for svelte, replace PR #47.

To make `vite-svelte` and `sveltekit` examples work I need to hack importing `@iconify/json-tools` and split declarations:
```ts
import pkg from '@iconify/json-tools'
...
const { SVG, Collection } = pkg
```

@bluwy, @dominikg both examples working with default templates: `vite-svelte` exmaple was using `ts` variant to make it working with `@iconify/json-tools` (will not work with `"type": "module"` and using `esm` import for `@iconify/json-tools` since it only provides `cjs` modules).

I'm working to provide `mjs` and `cjs` for `@iconify/json` (PR pushed) and `@iconify/json-tools` modules, when both published we only need to update dependencies and undo the import for `@iconify/json-tools`.

2021-09-13 11:40 UTC, bluwy approved these changes

2021-09-13 11:44 UTC, userquin commented
@antfu maybe splitting `@iconify/json-tools` is not desired and merging this PR should be postponed until I finish the PR for `@iconify/json-tools`. I don't know how much time will take to /cc @cyberalien to publish once I finish the PR.

2021-09-13 11:59 UTC, antfu reviewed
That's cool, I see the implementation much cleaner, nice work!

2021-09-13 11:59 UTC, antfu commented on examples/sveltekit/.eslintrc.cjs
> +		'svelte3/typescript': () => require('typescript')
Could we omit this eslint here since we already provide one in the root?

2021-09-13 11:59 UTC, antfu commented on examples/sveltekit/src/app.html
> +	</head>
Let's use 2 spaces

2021-09-13 11:59 UTC, antfu commented on examples/vite-svelte/package.json
> +  "eslintConfig": {
same as here, let's remove it.

2021-09-13 11:59 UTC, antfu commented on src/index.ts
> +    enforce,
We could always be `pre`, I see no harm for that.

2021-09-13 12:00 UTC, antfu commented
And I am fine with the import workaround for `@iconify/json-tools`

2021-09-13 12:01 UTC, userquin commented on examples/sveltekit/.eslintrc.cjs
> +		'svelte3/typescript': () => require('typescript')
This is the default from `svelte-kit`, I don't want change it...

2021-09-13 12:04 UTC, userquin commented on examples/sveltekit/src/app.html
> +	</head>
I'll change it, seems  the template includes tabs...

2021-09-13 12:08 UTC, userquin commented on examples/vite-svelte/package.json
> +  "eslintConfig": {
This is the default from svelte template, I don't want change it...

2021-09-13 12:11 UTC, userquin commented
About the `eslint` ask to @dominikg, I don't want to break defaults...

2021-09-13 12:12 UTC, antfu commented
I think the eslint if more for the best practice, while in our example our focus is to show the minimal setup requirements.

2021-09-13 14:20 UTC, bluwy requested changes

2021-09-13 14:20 UTC, bluwy commented on examples/sveltekit/tsconfig.json
> +			"unplugin-icons/types/svelte"
We should move the `types` here to `global.d.ts` instead, e.g.

```
/// <reference types="unplugin-icons/types/svelte" />
```

so we don't override the types here.

2021-09-13 14:20 UTC, bluwy commented on examples/vite-svelte/tsconfig.json
> +      "unplugin-icons/types/svelte"
Same here

2021-09-13 14:26 UTC, bluwy approved these changes

2021-09-14 02:05 UTC, merged

2022-02-02 13:57 UTC, vhscom commented on examples/sveltekit/src/app.html
> +	</head>
All SvelteKit projects use tabs by default. Tabs were created for indentation.